LANGS = {
    "Русский (Russian)": {
        "tab_monitor": "Монитор",
        "tab_speed": "Проверка скорости",
        "tab_settings": "Настройки",
        "tab_about": "О программе",
        "location": "Локация",
        "vpn_on": "VPN/Proxy подключено ",
        "vpn_off": "Без VPN/Proxy ",
        "sys_speed_title": "Системная скорость интернета",
        "traffic_title": "Потребление трафика за сессию",
        "traffic_recv": "Получено",
        "traffic_sent": "Отдано",
        "traffic_total": "Всего",
        "net_monitor_btn": "Мониторинг процессов",
        "net_monitor_title": "Мониторинг процессов",
        "net_monitor_process": "Процесс",
        "net_monitor_conns": "Подкл.",
        "net_monitor_sess_recv": "↓ Сессия",
        "net_monitor_sess_sent": "↑ Сессия",
        "net_monitor_no_data": "Нет активных соединений",
        "download": "Загрузка",
        "upload": "Отдача",
        "latency_label": "Задержка",
        "dns_title": "Проверка отклика (ping)",
        "speed_check_title": "Проверка скорости соединения",
        "settings_title": "Настройки",
        "speed_server_label": "Сервер проверки скорости:",
        "measure_btn": "Измерить",
        "cancel_btn": "Отменить",
        "testing": "Замер...",
        "ver_title": "Версия",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "О программе",
        "about_desc": "Программа с открытым кодом для мониторинга состояния сети в реальном времени. Отображает системную скорость интернета, время отклика до DNS-серверов популярных провайдеров, а также позволяет проверить скорость соединения через внешние серверы.",
        "links_title": "Ссылки",
        "ip_freq_label": "Частота обновления данных сети",
        "reset_btn": "Сброс настроек",
        "reset_dialog_msg": "Вы хотите сбросить только настройки или удалить полностью все параметры приложения (включая пользовательские IP для проверки ping и историю проверки скорости)?",
        "reset_settings_only_btn": "Удалить только настройки",
        "reset_all_btn": "Удалить все параметры",
        "lang_label": "Язык (Language)",
        "startup_label": "Запускать при старте Windows",
        "tray_label": "Работать в трее",
        "notify_ip": "Уведомлять при смене IP",
        "notify_conn_loss_label": "Уведомлять при потере связи",
        "notify_conn_lost_msg": "Потеряно соединение",
        "notify_conn_restored_msg": "Восстановлено соединение",
        "notify_ip_msg": "Изменился IP адрес. Новый регион: {region}",
        "f_5s": "5 секунд",
        "f_10s": "10 секунд",
        "f_30s": "30 секунд",
        "f_1m": "1 минута",
        "f_2m": "2 минуты",
        "f_5m": "5 минут",
        "f_10m": "10 минут",
        "tray_open": "Открыть",
        "tray_settings": "Настройки",
        "tray_speed_check": "Проверка скорости",
        "tray_exit": "Выход",
        "custom_dns_label": "IP для проверки ping",
        "dns_name_ph": "Название",
        "dns_host_ph": "IP / Хост",
        "dns_manage_btn": "Управление",
        "dns_window_title": "IP для проверки ping",
        "dns_add_btn": "Добавить",
        "speed_history_title": "История тестов",
        "speed_history_empty": "Тестов ещё нет",
        "speed_hist_date": "Дата",
        "speed_hist_server": "Сервер",
        "speed_history_clear": "Очистить",
        "proc_monitor_bg_label": "Мониторинг процессов в фоне",
        "tray_proc_monitor": "Мониторинг процессов",
        "update_check_label": "Проверять обновления при запуске",
        "update_checking": "Проверка доступности обновления...",
        "update_uptodate": "Вы используете актуальную версию программы",
        "update_available": "Доступно обновление {ver}! Установить?",
        "update_error": "Не удалось проверить обновления",
        "update_manual_btn": "Проверить обновления",
        "update_popup_title": "Доступно обновление",
        "update_popup_body": "Версия {ver} доступна для установки. Обновить сейчас?",
        "update_install_btn": "Установить",
        "cancel_btn": "Отмена",
        "update_progress_title": "Обновление программы",
        "update_downloading": "Загрузка обновления...",
        "update_extracting": "Распаковка файлов...",
        "update_restarting": "Перезапуск...",
        "notify_region_label": "Уведомлять при смене региона",
        "notify_region_msg": "Сменился регион: {region}",
        "always_on_top_label": "Поверх всех окон",
        "notify_conn_loss_label": "Уведомлять при потере связи",
        "ip_server_label": "Сервер проверки IP",
        "logs_btn": "Логи",
        "logs_save_btn": "Сохранить в файл",
        "logs_window_title": "Логи",
        "auto_logging_label": "Автоматическое логирование",
        "logging_disabled_msg": "Логирование отключено.\nАктивируйте параметр \"Автоматическое логирование\" в настройках.",
        "logs_pause_btn": "Пауза",
        "logs_resume_btn": "Продолжить",
        "ctx_copy": "Копировать",
        "system_lang": "Системный язык",
        "settings_section_general": "Общие",
        "settings_section_network": "Диагностика сети",
        "settings_section_notifications": "Уведомления",
    },
    "English (English)": {
        "tab_monitor": "Monitor",
        "tab_speed": "Speed Check",
        "tab_settings": "Settings",
        "tab_about": "About",
        "location": "Location",
        "vpn_on": "VPN/Proxy enabled ",
        "vpn_off": "VPN/Proxy disabled ",
        "sys_speed_title": "System Internet Speed",
        "traffic_title": "Session Traffic Usage",
        "traffic_recv": "Received",
        "traffic_sent": "Sent",
        "traffic_total": "Total",
        "net_monitor_btn": "Process Monitor",
        "net_monitor_title": "Process Network Monitor",
        "net_monitor_process": "Process",
        "net_monitor_conns": "Conn.",
        "net_monitor_sess_recv": "↓ Session",
        "net_monitor_sess_sent": "↑ Session",
        "net_monitor_no_data": "No active connections",
        "download": "Download",
        "upload": "Upload",
        "latency_label": "Latency",
        "dns_title": "Ping Latency Check",
        "speed_check_title": "Internet Speed Test",
        "settings_title": "Settings",
        "speed_server_label": "Speed Test Server:",
        "measure_btn": "Measure",
        "cancel_btn": "Cancel",
        "testing": "Testing...",
        "ver_title": "Version",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "About Program",
        "about_desc": "Open-source software for real-time network monitoring. Displays system internet speed, DNS response times to popular providers, and allows you to test connection speed via external servers.",
        "links_title": "Links",
        "ip_freq_label": "Network Info Update Interval",
        "reset_btn": "Reset to Default",
        "reset_dialog_msg": "Do you want to reset only the settings, or delete all app data (including custom ping IPs and speed test history)?",
        "reset_settings_only_btn": "Reset settings only",
        "reset_all_btn": "Delete all data",
        "lang_label": "Language",
        "startup_label": "Run on Windows Startup",
        "tray_label": "Work in Tray",
        "notify_ip": "Notify on IP change",
        "notify_conn_loss_label": "Notify on connection loss",
        "notify_conn_lost_msg": "Connection lost",
        "notify_conn_restored_msg": "Connection restored",
        "notify_ip_msg": "IP address changed. New region: {region}",
        "msg_ip_body": "New IP: ",
        "f_5s": "5 seconds",
        "f_10s": "10 seconds",
        "f_30s": "30 seconds",
        "f_1m": "1 minute",
        "f_2m": "2 minutes",
        "f_5m": "5 minutes",
        "f_10m": "10 minutes",
        "tray_open": "Open",
        "tray_settings": "Settings",
        "tray_speed_check": "Speed Check",
        "tray_exit": "Exit",
        "custom_dns_label": "Ping targets",
        "dns_name_ph": "Name",
        "dns_host_ph": "IP / Host",
        "dns_manage_btn": "Manage",
        "dns_window_title": "Ping Targets",
        "dns_add_btn": "Add",
        "speed_history_title": "Test History",
        "speed_history_empty": "No tests yet",
        "speed_hist_date": "Date",
        "speed_hist_server": "Server",
        "speed_history_clear": "Clear",
        "proc_monitor_bg_label": "Process monitor in background",
        "tray_proc_monitor": "Process Monitor",
        "update_check_label": "Check for updates on startup",
        "update_checking": "Checking for updates...",
        "update_uptodate": "You are using the latest version",
        "update_available": "Update {ver} available! Install?",
        "update_error": "Failed to check for updates",
        "update_manual_btn": "Check for updates",
        "update_popup_title": "Update available",
        "update_popup_body": "Version {ver} is available. Install now?",
        "update_install_btn": "Install",
        "cancel_btn": "Cancel",
        "update_progress_title": "Updating...",
        "update_downloading": "Downloading update...",
        "update_extracting": "Extracting files...",
        "update_restarting": "Restarting...",
        "notify_region_label": "Notify on region change",
        "notify_region_msg": "Region changed: {region}",
        "always_on_top_label": "Always on top",
        "notify_conn_loss_label": "Notify on connection loss",
        "ip_server_label": "IP Check Server",
        "logs_btn": "Logs",
        "logs_save_btn": "Save to file",
        "logs_window_title": "Logs",
        "auto_logging_label": "Auto Logging",
        "logging_disabled_msg": "Logging is disabled.\nActivate \"Auto Logging\" in Settings to enable it.",
        "logs_pause_btn": "Pause",
        "logs_resume_btn": "Resume",
        "ctx_copy": "Copy",
        "system_lang": "System Language",
        "settings_section_general": "General",
        "settings_section_network": "Network Diagnostics",
        "settings_section_notifications": "Notifications",
    },
    "Українська (Ukrainian)": {
        "tab_monitor": "Монітор",
        "tab_speed": "Перевірка швидкості",
        "tab_settings": "Налаштування",
        "tab_about": "Про програму",
        "location": "Локація",
        "vpn_on": "VPN/Proxy увімкнено ",
        "vpn_off": "Без VPN/Proxy ",
        "sys_speed_title": "Системна швидкість інтернету",
        "traffic_title": "Споживання трафіку за сесію",
        "traffic_recv": "Отримано",
        "traffic_sent": "Відправлено",
        "traffic_total": "Всього",
        "net_monitor_btn": "Моніторинг процесів",
        "net_monitor_title": "Моніторинг процесів",
        "net_monitor_process": "Процес",
        "net_monitor_conns": "Підкл.",
        "net_monitor_sess_recv": "↓ Сесія",
        "net_monitor_sess_sent": "↑ Сесія",
        "net_monitor_no_data": "Немає активних з'єднань",
        "download": "Завантаження",
        "upload": "Відвантаження",
        "latency_label": "Затримка",
        "dns_title": "Перевірка відгуку (ping)",
        "speed_check_title": "Перевірка швидкості з'єднання",
        "settings_title": "Налаштування",
        "speed_server_label": "Сервер перевірки швидкості:",
        "measure_btn": "Виміряти",
        "cancel_btn": "Скасувати",
        "testing": "Замір...",
        "ver_title": "Версія",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "Про програму",
        "about_desc": "Програма з відкритим кодом для моніторингу стану мережі в реальному часі. Відображає системну швидкість інтернету, час відгуку до DNS-серверів популярних провайдерів та дозволяє перевірити швидкість через зовнішні сервери.",
        "links_title": "Посилання",
        "ip_freq_label": "Оновлення даних мережі",
        "reset_btn": "Скинути налаштування",
        "reset_dialog_msg": "Ви хочете скинути лише налаштування або видалити всі параметри додатку (включаючи IP для перевірки ping та історію тестів)?",
        "reset_settings_only_btn": "Скинути лише налаштування",
        "reset_all_btn": "Видалити всі параметри",
        "lang_label": "Мова (Language)",
        "startup_label": "Запускати при старті Windows",
        "tray_label": "Працювати в треї",
        "notify_ip": "Сповіщати при зміні IP",
        "notify_conn_loss_label": "Сповіщати при втраті зв'язку",
        "notify_conn_lost_msg": "З'єднання втрачено",
        "notify_conn_restored_msg": "З'єднання відновлено",
        "notify_ip_msg": "IP-адреса змінилась. Новий регіон: {region}",
        "msg_ip_body": "Новий IP: ",
        "f_5s": "5 секунд",
        "f_10s": "10 секунд",
        "f_30s": "30 секунд",
        "f_1m": "1 хвилина",
        "f_2m": "2 хвилини",
        "f_5m": "5 хвилин",
        "f_10m": "10 хвилин",
        "tray_open": "Відкрити",
        "tray_settings": "Налаштування",
        "tray_speed_check": "Перевірка швидкості",
        "tray_exit": "Вийти",
        "custom_dns_label": "IP для перевірки ping",
        "dns_name_ph": "Назва",
        "dns_host_ph": "IP / Хост",
        "dns_manage_btn": "Управління",
        "dns_window_title": "IP для перевірки ping",
        "dns_add_btn": "Додати",
        "speed_history_title": "Історія тестів",
        "speed_history_empty": "Тестів ще немає",
        "speed_hist_date": "Дата",
        "speed_hist_server": "Сервер",
        "speed_history_clear": "Очистити",
        "proc_monitor_bg_label": "Моніторинг процесів у фоні",
        "tray_proc_monitor": "Моніторинг процесів",
        "update_check_label": "Перевіряти оновлення при запуску",
        "update_checking": "Перевірка наявності оновлень...",
        "update_uptodate": "Ви використовуєте актуальну версію програми",
        "update_available": "Доступне оновлення {ver}! Встановити?",
        "update_error": "Не вдалося перевірити оновлення",
        "update_manual_btn": "Перевірити оновлення",
        "update_popup_title": "Доступне оновлення",
        "update_popup_body": "Версія {ver} доступна для встановлення. Оновити зараз?",
        "update_install_btn": "Встановити",
        "cancel_btn": "Скасувати",
        "update_progress_title": "Оновлення програми",
        "update_downloading": "Завантаження оновлення...",
        "update_extracting": "Розпакування файлів...",
        "update_restarting": "Перезапуск...",
        "notify_region_label": "Сповіщати про зміну регіону",
        "notify_region_msg": "Регіон змінився: {region}",
        "always_on_top_label": "Поверх усіх вікон",
        "notify_conn_loss_label": "Сповіщати при втраті зв'язку",
        "ip_server_label": "Сервер перевірки IP",
        "logs_btn": "Логи",
        "logs_save_btn": "Зберегти у файл",
        "logs_window_title": "Логи",
        "auto_logging_label": "Автоматичне логування",
        "logging_disabled_msg": "Логування вимкнено.\nАктивуйте параметр \"Автоматичне логування\" в налаштуваннях.",
        "logs_pause_btn": "Пауза",
        "logs_resume_btn": "Продовжити",
        "ctx_copy": "Копіювати",
        "system_lang": "Системна мова",
        "settings_section_general": "Загальні",
        "settings_section_network": "Діагностика мережі",
        "settings_section_notifications": "Сповіщення",
    },
    "简体中文 (Chinese)": {
        "tab_monitor": "监控",
        "tab_speed": "速度测试",
        "tab_settings": "设置",
        "tab_about": "关于",
        "location": "位置",
        "vpn_on": "VPN/代理已启用 ",
        "vpn_off": "未启用 VPN/代理 ",
        "sys_speed_title": "系统网速",
        "traffic_title": "本次会话流量",
        "traffic_recv": "接收",
        "traffic_sent": "发送",
        "traffic_total": "合计",
        "net_monitor_btn": "进程监控",
        "net_monitor_title": "进程网络监控",
        "net_monitor_process": "进程",
        "net_monitor_conns": "连接",
        "net_monitor_sess_recv": "↓ 会话",
        "net_monitor_sess_sent": "↑ 会话",
        "net_monitor_no_data": "无活动连接",
        "download": "下载",
        "upload": "上传",
        "latency_label": "延迟",
        "dns_title": "Ping 延迟检测",
        "speed_check_title": "网速测试",
        "settings_title": "设置",
        "speed_server_label": "测速服务器:",
        "measure_btn": "测速",
        "cancel_btn": "取消",
        "testing": "测试中...",
        "ver_title": "版本",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "关于程序",
        "about_desc": "实时网络监控的开源软件。显示系统网速、主流 DNS 提供商的响应时间，并允许通过外部服务器测试连接速度。",
        "links_title": "链接",
        "ip_freq_label": "网络信息更新频率",
        "reset_btn": "重置设置",
        "reset_dialog_msg": "您要仅重置设置，还是删除所有应用数据（包括自定义 ping IP 和测速记录）？",
        "reset_settings_only_btn": "仅重置设置",
        "reset_all_btn": "删除所有数据",
        "lang_label": "语言 (Language)",
        "startup_label": "开机自启动",
        "tray_label": "在托盘中运行",
        "notify_ip": "IP 变更提醒",
        "notify_conn_loss_label": "断网时发出通知",
        "notify_conn_lost_msg": "连接已断开",
        "notify_conn_restored_msg": "连接已恢复",
        "notify_ip_msg": "IP地址已更改。新地区: {region}",
        "msg_ip_body": "新 IP: ",
        "f_5s": "5 秒",
        "f_10s": "10 秒",
        "f_30s": "30 秒",
        "f_1m": "1 分钟",
        "f_2m": "2 分钟",
        "f_5m": "5 分钟",
        "f_10m": "10 分钟",
        "tray_open": "打开",
        "tray_settings": "设置",
        "tray_speed_check": "速度测试",
        "tray_exit": "退出",
        "custom_dns_label": "Ping 目标 IP",
        "dns_name_ph": "名称",
        "dns_host_ph": "IP / 主机",
        "dns_manage_btn": "管理",
        "dns_window_title": "Ping 目标",
        "dns_add_btn": "添加",
        "speed_history_title": "测速记录",
        "speed_history_empty": "暂无记录",
        "speed_hist_date": "日期",
        "speed_hist_server": "服务器",
        "speed_history_clear": "清空",
        "proc_monitor_bg_label": "后台进程监控",
        "tray_proc_monitor": "进程监控",
        "update_check_label": "启动时检查更新",
        "update_checking": "正在检查更新...",
        "update_uptodate": "您正在使用最新版本",
        "update_available": "有可用更新 {ver}！安装？",
        "update_error": "无法检查更新",
        "update_manual_btn": "检查更新",
        "update_popup_title": "有可用更新",
        "update_popup_body": "版本 {ver} 可供安装。立即更新？",
        "update_install_btn": "安装",
        "cancel_btn": "取消",
        "update_progress_title": "正在更新程序",
        "update_downloading": "正在下载更新...",
        "update_extracting": "正在解压文件...",
        "update_restarting": "正在重启...",
        "notify_region_label": "地区更改通知",
        "notify_region_msg": "地区已更改: {region}",
        "always_on_top_label": "置顶显示",
        "notify_conn_loss_label": "断网通知",
        "notify_region_label": "地区更改通知",
        "notify_region_msg": "地区已更改: {region}",
        "always_on_top_label": "置顶显示",
        "notify_conn_loss_label": "断网通知",
        "ip_server_label": "IP查询服务器",
        "logs_btn": "日志",
        "logs_save_btn": "保存到文件",
        "logs_window_title": "日志",
        "auto_logging_label": "自动日志记录",
        "logging_disabled_msg": "日志记录已禁用。\n请在设置中启用「自动日志记录」。",
        "logs_pause_btn": "暂停",
        "logs_resume_btn": "继续",
        "ctx_copy": "复制",
        "system_lang": "系统语言",
        "settings_section_general": "常规",
        "settings_section_network": "网络诊断",
        "settings_section_notifications": "通知",
    },
    "Deutsch (German)": {
        "tab_monitor": "Monitor",
        "tab_speed": "Geschwindigkeitstest",
        "tab_settings": "Einstellungen",
        "tab_about": "Über uns",
        "location": "Standort",
        "vpn_on": "VPN/Proxy aktiv ",
        "vpn_off": "Kein VPN/Proxy ",
        "sys_speed_title": "Systeminternetgeschwindigkeit",
        "traffic_title": "Sitzungsverbrauch",
        "traffic_recv": "Empfangen",
        "traffic_sent": "Gesendet",
        "traffic_total": "Gesamt",
        "net_monitor_btn": "Prozess-Monitor",
        "net_monitor_title": "Prozess-Netzwerkmonitor",
        "net_monitor_process": "Prozess",
        "net_monitor_conns": "Verb.",
        "net_monitor_sess_recv": "↓ Sitzung",
        "net_monitor_sess_sent": "↑ Sitzung",
        "net_monitor_no_data": "Keine aktiven Verbindungen",
        "download": "Download",
        "upload": "Upload",
        "latency_label": "Latenz",
        "dns_title": "Ping-Antwortzeit prüfen",
        "speed_check_title": "Internetgeschwindigkeitstest",
        "settings_title": "Einstellungen",
        "speed_server_label": "Testserver:",
        "measure_btn": "Messen",
        "cancel_btn": "Abbrechen",
        "testing": "Testet...",
        "ver_title": "Version",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "Über das Programm",
        "about_desc": "Open-Source-Software zur Netzwerküberwachung in Echtzeit. Zeigt die Systeminternetgeschwindigkeit, DNS-Antwortzeiten populärer Anbieter und ermöglicht Geschwindigkeitstests über externe Server.",
        "links_title": "Links",
        "ip_freq_label": "Netzwerk-Info Intervall",
        "reset_btn": "Zurücksetzen",
        "reset_dialog_msg": "Möchten Sie nur die Einstellungen zurücksetzen oder alle App-Daten löschen (einschließlich benutzerdefinierter Ping-IPs und Testergebnisse)?",
        "reset_settings_only_btn": "Nur Einstellungen zurücksetzen",
        "reset_all_btn": "Alle Daten löschen",
        "lang_label": "Sprache (Language)",
        "startup_label": "Mit Windows starten",
        "tray_label": "Im Tray arbeiten",
        "notify_ip": "IP-Wechsel melden",
        "notify_conn_loss_label": "Bei Verbindungsverlust melden",
        "notify_conn_lost_msg": "Verbindung getrennt",
        "notify_conn_restored_msg": "Verbindung wiederhergestellt",
        "notify_ip_msg": "IP-Adresse geändert. Neue Region: {region}",
        "msg_ip_body": "Neue IP: ",
        "f_5s": "5 Sekunden",
        "f_10s": "10 Sekunden",
        "f_30s": "30 Sekunden",
        "f_1m": "1 Minute",
        "f_2m": "2 Minuten",
        "f_5m": "5 Minuten",
        "f_10m": "10 Minuten",
        "tray_open": "Öffnen",
        "tray_settings": "Einstellungen",
        "tray_speed_check": "Geschwindigkeitstest",
        "tray_exit": "Beenden",
        "custom_dns_label": "Ping-Ziele",
        "dns_name_ph": "Name",
        "dns_host_ph": "IP / Host",
        "dns_manage_btn": "Verwalten",
        "dns_window_title": "Ping-Ziele",
        "dns_add_btn": "Hinzufügen",
        "speed_history_title": "Testergebnisse",
        "speed_history_empty": "Noch keine Tests",
        "speed_hist_date": "Datum",
        "speed_hist_server": "Server",
        "speed_history_clear": "Löschen",
        "proc_monitor_bg_label": "Prozessüberwachung im Hintergrund",
        "tray_proc_monitor": "Prozess-Monitor",
        "update_check_label": "Updates beim Start prüfen",
        "update_checking": "Auf Updates prüfen...",
        "update_uptodate": "Sie verwenden die neueste Version",
        "update_available": "Update {ver} verfügbar! Installieren?",
        "update_error": "Update-Prüfung fehlgeschlagen",
        "update_manual_btn": "Auf Updates prüfen",
        "update_popup_title": "Update verfügbar",
        "update_popup_body": "Version {ver} ist verfügbar. Jetzt installieren?",
        "update_install_btn": "Installieren",
        "cancel_btn": "Abbrechen",
        "update_progress_title": "Programm wird aktualisiert",
        "update_downloading": "Update wird heruntergeladen...",
        "update_extracting": "Dateien werden entpackt...",
        "update_restarting": "Neustart...",
        "notify_region_label": "Bei Regionswechsel benachrichtigen",
        "notify_region_msg": "Region gewechselt: {region}",
        "always_on_top_label": "Immer im Vordergrund",
        "notify_conn_loss_label": "Bei Verbindungsverlust benachrichtigen",
        "notify_region_label": "Bei Regionswechsel benachrichtigen",
        "notify_region_msg": "Region gewechselt: {region}",
        "always_on_top_label": "Immer im Vordergrund",
        "notify_conn_loss_label": "Bei Verbindungsverlust benachrichtigen",
        "ip_server_label": "IP-Prüfserver",
        "logs_btn": "Protokoll",
        "logs_save_btn": "In Datei speichern",
        "logs_window_title": "Protokoll",
        "auto_logging_label": "Automatische Protokollierung",
        "logging_disabled_msg": "Protokollierung ist deaktiviert.\nAktivieren Sie \"Automatische Protokollierung\" in den Einstellungen.",
        "logs_pause_btn": "Pause",
        "logs_resume_btn": "Fortsetzen",
        "ctx_copy": "Kopieren",
        "system_lang": "Systemsprache",
        "settings_section_general": "Allgemein",
        "settings_section_network": "Netzwerkdiagnose",
        "settings_section_notifications": "Benachrichtigungen",
    },
    "Polski (Polish)": {
        "tab_monitor": "Monitor",
        "tab_speed": "Test prędkości",
        "tab_settings": "Ustawienia",
        "tab_about": "O programie",
        "location": "Lokalizacja",
        "vpn_on": "VPN/Proxy włączone ",
        "vpn_off": "Bez VPN/Proxy ",
        "sys_speed_title": "Systemowa prędkość internetu",
        "traffic_title": "Ruch sieciowy sesji",
        "traffic_recv": "Pobrano",
        "traffic_sent": "Wysłano",
        "traffic_total": "Łącznie",
        "net_monitor_btn": "Monitor procesów",
        "net_monitor_title": "Monitor sieci procesów",
        "net_monitor_process": "Proces",
        "net_monitor_conns": "Poł.",
        "net_monitor_sess_recv": "↓ Sesja",
        "net_monitor_sess_sent": "↑ Sesja",
        "net_monitor_no_data": "Brak aktywnych połączeń",
        "download": "Pobieranie",
        "upload": "Wysyłanie",
        "latency_label": "Opóźnienie",
        "dns_title": "Sprawdzanie ping",
        "speed_check_title": "Test prędkości połączenia",
        "settings_title": "Ustawienia",
        "speed_server_label": "Serwer testowy:",
        "measure_btn": "Zmierz",
        "cancel_btn": "Anuluj",
        "testing": "Test...",
        "ver_title": "Wersja",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "O programie",
        "about_desc": "Oprogramowanie open-source do monitorowania sieci w czasie rzeczywistym. Wyświetla systemową prędkość internetu, czas odpowiedzi serwerów DNS i umożliwia test połączenia przez zewnętrzne serwery.",
        "links_title": "Linki",
        "ip_freq_label": "Aktualizacja info o sieci",
        "reset_btn": "Resetuj ustawienia",
        "reset_dialog_msg": "Czy chcesz zresetować tylko ustawienia, czy usunąć wszystkie dane aplikacji (w tym niestandardowe IP ping i historię testów)?",
        "reset_settings_only_btn": "Resetuj tylko ustawienia",
        "reset_all_btn": "Usuń wszystkie dane",
        "lang_label": "Język (Language)",
        "startup_label": "Uruchamiaj przy starcie systemu",
        "tray_label": "Pracuj w zasobniku",
        "notify_ip": "Powiadom o zmianie IP",
        "notify_conn_loss_label": "Powiadamiaj o utracie połączenia",
        "notify_conn_lost_msg": "Połączenie utracone",
        "notify_conn_restored_msg": "Połączenie przywrócone",
        "notify_ip_msg": "Adres IP zmieniony. Nowy region: {region}",
        "msg_ip_body": "Nowy IP: ",
        "f_5s": "5 sekund",
        "f_10s": "10 sekund",
        "f_30s": "30 sekund",
        "f_1m": "1 minuta",
        "f_2m": "2 minuty",
        "f_5m": "5 minut",
        "f_10m": "10 minut",
        "tray_open": "Otwórz",
        "tray_settings": "Ustawienia",
        "tray_speed_check": "Test prędkości",
        "tray_exit": "Wyjście",
        "custom_dns_label": "Cele ping",
        "dns_name_ph": "Nazwa",
        "dns_host_ph": "IP / Host",
        "dns_manage_btn": "Zarządzaj",
        "dns_window_title": "Cele ping",
        "dns_add_btn": "Dodaj",
        "speed_history_title": "Historia testów",
        "speed_history_empty": "Brak testów",
        "speed_hist_date": "Data",
        "speed_hist_server": "Serwer",
        "speed_history_clear": "Wyczyść",
        "proc_monitor_bg_label": "Monitor procesów w tle",
        "tray_proc_monitor": "Monitor procesów",
        "update_check_label": "Sprawdzaj aktualizacje przy starcie",
        "update_checking": "Sprawdzanie aktualizacji...",
        "update_uptodate": "Używasz najnowszej wersji programu",
        "update_available": "Dostępna aktualizacja {ver}! Zainstalować?",
        "update_error": "Nie udało się sprawdzić aktualizacji",
        "update_manual_btn": "Sprawdź aktualizacje",
        "update_popup_title": "Dostępna aktualizacja",
        "update_popup_body": "Wersja {ver} jest dostępna. Zainstalować teraz?",
        "update_install_btn": "Zainstaluj",
        "cancel_btn": "Anuluj",
        "update_progress_title": "Aktualizacja programu",
        "update_downloading": "Pobieranie aktualizacji...",
        "update_extracting": "Rozpakowywanie plików...",
        "update_restarting": "Ponowne uruchomienie...",
        "notify_region_label": "Powiadom przy zmianie regionu",
        "notify_region_msg": "Region zmieniony: {region}",
        "always_on_top_label": "Zawsze na wierzchu",
        "notify_conn_loss_label": "Powiadom o utracie połączenia",
        "notify_region_label": "Powiadom przy zmianie regionu",
        "notify_region_msg": "Region zmieniony: {region}",
        "always_on_top_label": "Zawsze na wierzchu",
        "notify_conn_loss_label": "Powiadom o utracie połączenia",
        "ip_server_label": "Serwer sprawdzania IP",
        "logs_btn": "Logi",
        "logs_save_btn": "Zapisz do pliku",
        "logs_window_title": "Logi",
        "auto_logging_label": "Automatyczne logowanie",
        "logging_disabled_msg": "Logowanie jest wyłączone.\nAktywuj opcję \"Automatyczne logowanie\" w ustawieniach.",
        "logs_pause_btn": "Pauza",
        "logs_resume_btn": "Wznów",
        "ctx_copy": "Kopiuj",
        "system_lang": "Język systemowy",
        "settings_section_general": "Ogólne",
        "settings_section_network": "Diagnostyka sieci",
        "settings_section_notifications": "Powiadomienia",
    },
    "Español (Spanish)": {
        "tab_monitor": "Monitor",
        "tab_speed": "Prueba de velocidad",
        "tab_settings": "Ajustes",
        "tab_about": "Acerca de",
        "location": "Ubicación",
        "vpn_on": "VPN/Proxy activo ",
        "vpn_off": "Sin VPN/Proxy ",
        "sys_speed_title": "Velocidad de internet del sistema",
        "traffic_title": "Tráfico de la sesión",
        "traffic_recv": "Recibido",
        "traffic_sent": "Enviado",
        "traffic_total": "Total",
        "net_monitor_btn": "Monitor de procesos",
        "net_monitor_title": "Monitor de red por proceso",
        "net_monitor_process": "Proceso",
        "net_monitor_conns": "Conn.",
        "net_monitor_sess_recv": "↓ Sesión",
        "net_monitor_sess_sent": "↑ Sesión",
        "net_monitor_no_data": "Sin conexiones activas",
        "download": "Descarga",
        "upload": "Subida",
        "latency_label": "Latencia",
        "dns_title": "Verificación de ping",
        "speed_check_title": "Prueba de velocidad de conexión",
        "settings_title": "Ajustes",
        "speed_server_label": "Servidor de prueba:",
        "measure_btn": "Medir",
        "cancel_btn": "Cancelar",
        "testing": "Probando...",
        "ver_title": "Versión",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "Sobre el programa",
        "about_desc": "Software de código abierto para el monitoreo de red en tiempo real. Muestra la velocidad del sistema, tiempos de respuesta DNS y permite probar la velocidad de conexión mediante servidores externos.",
        "links_title": "Enlaces",
        "ip_freq_label": "Actualización de red",
        "reset_btn": "Restablecer",
        "reset_dialog_msg": "¿Desea restablecer solo la configuración o eliminar todos los datos de la aplicación (incluidas las IPs de ping personalizadas y el historial de pruebas)?",
        "reset_settings_only_btn": "Restablecer solo configuración",
        "reset_all_btn": "Eliminar todos los datos",
        "lang_label": "Idioma (Language)",
        "startup_label": "Iniciar con Windows",
        "tray_label": "Trabajar en bandeja",
        "notify_ip": "Notificar cambio de IP",
        "notify_conn_loss_label": "Notificar pérdida de conexión",
        "notify_conn_lost_msg": "Conexión perdida",
        "notify_conn_restored_msg": "Conexión restaurada",
        "notify_ip_msg": "IP cambiada. Nueva región: {region}",
        "msg_ip_body": "Nueva IP: ",
        "f_5s": "5 segundos",
        "f_10s": "10 segundos",
        "f_30s": "30 segundos",
        "f_1m": "1 minuto",
        "f_2m": "2 minutos",
        "f_5m": "5 minutos",
        "f_10m": "10 minutos",
        "tray_open": "Abrir",
        "tray_settings": "Ajustes",
        "tray_speed_check": "Prueba de velocidad",
        "tray_exit": "Salir",
        "custom_dns_label": "IPs para ping",
        "dns_name_ph": "Nombre",
        "dns_host_ph": "IP / Host",
        "dns_manage_btn": "Gestionar",
        "dns_window_title": "IPs para ping",
        "dns_add_btn": "Agregar",
        "speed_history_title": "Historial de pruebas",
        "speed_history_empty": "Sin pruebas",
        "speed_hist_date": "Fecha",
        "speed_hist_server": "Servidor",
        "speed_history_clear": "Borrar",
        "proc_monitor_bg_label": "Monitor de procesos en segundo plano",
        "tray_proc_monitor": "Monitor de procesos",
        "update_check_label": "Buscar actualizaciones al iniciar",
        "update_checking": "Buscando actualizaciones...",
        "update_uptodate": "Estás usando la versión más reciente",
        "update_available": "¡Actualización {ver} disponible! ¿Instalar?",
        "update_error": "No se pudieron verificar las actualizaciones",
        "update_manual_btn": "Buscar actualizaciones",
        "update_popup_title": "Actualización disponible",
        "update_popup_body": "La versión {ver} está disponible. ¿Instalar ahora?",
        "update_install_btn": "Instalar",
        "cancel_btn": "Cancelar",
        "update_progress_title": "Actualizando programa",
        "update_downloading": "Descargando actualización...",
        "update_extracting": "Extrayendo archivos...",
        "update_restarting": "Reiniciando...",
        "notify_region_label": "Notificar al cambiar de región",
        "notify_region_msg": "Región cambiada: {region}",
        "always_on_top_label": "Siempre visible",
        "notify_conn_loss_label": "Notificar al perder conexión",
        "ip_server_label": "Servidor de verificación IP",
        "logs_btn": "Registros",
        "logs_save_btn": "Guardar en archivo",
        "logs_window_title": "Registros",
        "auto_logging_label": "Registro automático",
        "logging_disabled_msg": "El registro está desactivado.\nActive \"Registro automático\" en la configuración.",
        "logs_pause_btn": "Pausar",
        "logs_resume_btn": "Reanudar",
        "ctx_copy": "Copiar",
        "system_lang": "Idioma del sistema",
        "settings_section_general": "General",
        "settings_section_network": "Diagnóstico de red",
        "settings_section_notifications": "Notificaciones",
    },
    "Français (French)": {
        "tab_monitor": "Moniteur",
        "tab_speed": "Test de vitesse",
        "tab_settings": "Paramètres",
        "tab_about": "À propos",
        "location": "Emplacement",
        "vpn_on": "VPN/Proxy activé ",
        "vpn_off": "Sans VPN/Proxy ",
        "sys_speed_title": "Vitesse internet du système",
        "traffic_title": "Trafic de la session",
        "traffic_recv": "Reçu",
        "traffic_sent": "Envoyé",
        "traffic_total": "Total",
        "net_monitor_btn": "Moniteur de processus",
        "net_monitor_title": "Moniteur réseau par processus",
        "net_monitor_process": "Processus",
        "net_monitor_conns": "Conn.",
        "net_monitor_sess_recv": "↓ Session",
        "net_monitor_sess_sent": "↑ Session",
        "net_monitor_no_data": "Aucune connexion active",
        "download": "Téléchargement",
        "upload": "Envoi",
        "latency_label": "Latence",
        "dns_title": "Vérification du ping",
        "speed_check_title": "Test de vitesse de connexion",
        "settings_title": "Paramètres",
        "speed_server_label": "Serveur de test :",
        "measure_btn": "Mesurer",
        "cancel_btn": "Annuler",
        "testing": "Test...",
        "ver_title": "Version",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "À propos du programme",
        "about_desc": "Logiciel open-source pour la surveillance réseau en temps réel. Affiche la vitesse internet du système, les temps de réponse DNS et permet de tester la vitesse via des serveurs externes.",
        "links_title": "Liens",
        "ip_freq_label": "Mise à jour réseau ",
        "reset_btn": "Réinitialiser",
        "reset_dialog_msg": "Souhaitez-vous réinitialiser uniquement les paramètres ou supprimer toutes les données de l'application (y compris les IP ping personnalisées et l'historique des tests) ?",
        "reset_settings_only_btn": "Réinitialiser les paramètres",
        "reset_all_btn": "Supprimer toutes les données",
        "lang_label": "Langue (Language)",
        "startup_label": "Lancer avec Windows",
        "tray_label": "Travailler dans la barre",
        "notify_ip": "Alerte changement d'IP",
        "notify_conn_loss_label": "Alerte perte de connexion",
        "notify_conn_lost_msg": "Connexion perdue",
        "notify_conn_restored_msg": "Connexion rétablie",
        "notify_ip_msg": "IP modifiée. Nouvelle région : {region}",
        "msg_ip_body": "Nouvelle IP : ",
        "f_5s": "5 secondes",
        "f_10s": "10 secondes",
        "f_30s": "30 secondes",
        "f_1m": "1 minute",
        "f_2m": "2 minutes",
        "f_5m": "5 minutes",
        "f_10m": "10 minutes",
        "tray_open": "Ouvrir",
        "tray_settings": "Paramètres",
        "tray_speed_check": "Test de vitesse",
        "tray_exit": "Quitter",
        "custom_dns_label": "IP à pinger ",
        "dns_name_ph": "Nom",
        "dns_host_ph": "IP / Hôte",
        "dns_manage_btn": "Gérer",
        "dns_window_title": "IP à pinger",
        "dns_add_btn": "Ajouter",
        "speed_history_title": "Historique des tests",
        "speed_history_empty": "Aucun test",
        "speed_hist_date": "Date",
        "speed_hist_server": "Serveur",
        "speed_history_clear": "Effacer",
        "proc_monitor_bg_label": "Surveillance des processus en arrière-plan",
        "tray_proc_monitor": "Moniteur de processus",
        "update_check_label": "Vérifier les mises à jour au démarrage",
        "update_checking": "Vérification des mises à jour...",
        "update_uptodate": "Vous utilisez la version la plus récente",
        "update_available": "Mise à jour {ver} disponible ! Installer ?",
        "update_error": "Impossible de vérifier les mises à jour",
        "update_manual_btn": "Vérifier les mises à jour",
        "update_popup_title": "Mise à jour disponible",
        "update_popup_body": "La version {ver} est disponible. Installer maintenant ?",
        "update_install_btn": "Installer",
        "cancel_btn": "Annuler",
        "update_progress_title": "Mise à jour en cours",
        "update_downloading": "Téléchargement de la mise à jour...",
        "update_extracting": "Extraction des fichiers...",
        "update_restarting": "Redémarrage...",
        "notify_region_label": "Notifier lors du changement de région",
        "notify_region_msg": "Région changée : {region}",
        "always_on_top_label": "Toujours visible",
        "notify_conn_loss_label": "Notifier en cas de perte de connexion",
        "notify_region_label": "Notifier lors du changement de région",
        "notify_region_msg": "Région changée : {region}",
        "always_on_top_label": "Toujours visible",
        "notify_conn_loss_label": "Notifier en cas de perte de connexion",
        "ip_server_label": "Serveur de vérification IP",
        "logs_btn": "Journaux",
        "logs_save_btn": "Enregistrer dans un fichier",
        "logs_window_title": "Journaux",
        "auto_logging_label": "Journalisation automatique",
        "logging_disabled_msg": "La journalisation est désactivée.\nActivez \"Journalisation automatique\" dans les paramètres.",
        "logs_pause_btn": "Pause",
        "logs_resume_btn": "Reprendre",
        "ctx_copy": "Copier",
        "system_lang": "Langue du système",
        "settings_section_general": "Général",
        "settings_section_network": "Diagnostic réseau",
        "settings_section_notifications": "Notifications",
    },
    "Português (Portuguese)": {
        "tab_monitor": "Monitor",
        "tab_speed": "Teste de velocidade",
        "tab_settings": "Configurações",
        "tab_about": "Sobre",
        "location": "Localização",
        "vpn_on": "VPN/Proxy ativo ",
        "vpn_off": "Sem VPN/Proxy ",
        "sys_speed_title": "Velocidade de internet do sistema",
        "traffic_title": "Tráfego da sessão",
        "traffic_recv": "Recebido",
        "traffic_sent": "Enviado",
        "traffic_total": "Total",
        "net_monitor_btn": "Monitor de processos",
        "net_monitor_title": "Monitor de rede por processo",
        "net_monitor_process": "Processo",
        "net_monitor_conns": "Con.",
        "net_monitor_sess_recv": "↓ Sessão",
        "net_monitor_sess_sent": "↑ Sessão",
        "net_monitor_no_data": "Sem conexões ativas",
        "download": "Download",
        "upload": "Upload",
        "latency_label": "Latência",
        "dns_title": "Verificação de ping",
        "speed_check_title": "Teste de velocidade de conexão",
        "settings_title": "Configurações",
        "speed_server_label": "Servidor de teste:",
        "measure_btn": "Medir",
        "cancel_btn": "Cancelar",
        "testing": "Testando...",
        "ver_title": "Versão",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "Sobre o programa",
        "about_desc": "Software de código aberto para monitoramento de rede em tempo real. Exibe a velocidade de internet do sistema, tempos de resposta DNS e permite testar a velocidade via servidores externos.",
        "links_title": "Links",
        "ip_freq_label": "Atualização de rede",
        "reset_btn": "Redefinir",
        "reset_dialog_msg": "Deseja redefinir apenas as configurações ou excluir todos os dados do aplicativo (incluindo IPs de ping personalizados e histórico de testes)?",
        "reset_settings_only_btn": "Redefinir apenas configurações",
        "reset_all_btn": "Excluir todos os dados",
        "lang_label": "Idioma (Language)",
        "startup_label": "Iniciar com o Windows",
        "tray_label": "Trabalhar na bandeja",
        "notify_ip": "Notificar mudança de IP",
        "notify_conn_loss_label": "Notificar perda de conexão",
        "notify_conn_lost_msg": "Conexão perdida",
        "notify_conn_restored_msg": "Conexão restaurada",
        "notify_ip_msg": "IP alterado. Nova região: {region}",
        "msg_ip_body": "Novo IP: ",
        "f_5s": "5 segundos",
        "f_10s": "10 segundos",
        "f_30s": "30 segundos",
        "f_1m": "1 minuto",
        "f_2m": "2 minutos",
        "f_5m": "5 minutos",
        "f_10m": "10 minutos",
        "tray_open": "Abrir",
        "tray_settings": "Configurações",
        "tray_speed_check": "Teste de velocidade",
        "tray_exit": "Sair",
        "custom_dns_label": "IPs para ping",
        "dns_name_ph": "Nome",
        "dns_host_ph": "IP / Host",
        "dns_manage_btn": "Gerenciar",
        "dns_window_title": "IPs para ping",
        "dns_add_btn": "Adicionar",
        "speed_history_title": "Histórico de testes",
        "speed_history_empty": "Sem testes ainda",
        "speed_hist_date": "Data",
        "speed_hist_server": "Servidor",
        "speed_history_clear": "Limpar",
        "proc_monitor_bg_label": "Monitor de processos em segundo plano",
        "tray_proc_monitor": "Monitor de processos",
        "update_check_label": "Verificar atualizações ao iniciar",
        "update_checking": "Verificando atualizações...",
        "update_uptodate": "Você está usando a versão mais recente",
        "update_available": "Atualização {ver} disponível! Instalar?",
        "update_error": "Falha ao verificar atualizações",
        "update_manual_btn": "Verificar atualizações",
        "update_popup_title": "Atualização disponível",
        "update_popup_body": "A versão {ver} está disponível. Instalar agora?",
        "update_install_btn": "Instalar",
        "cancel_btn": "Cancelar",
        "update_progress_title": "Atualizando programa",
        "update_downloading": "Baixando atualização...",
        "update_extracting": "Extraindo arquivos...",
        "update_restarting": "Reiniciando...",
        "notify_region_label": "Notificar ao mudar de região",
        "notify_region_msg": "Região alterada: {region}",
        "always_on_top_label": "Sempre no topo",
        "notify_conn_loss_label": "Notificar ao perder conexão",
        "ip_server_label": "Servidor de verificação de IP",
        "logs_btn": "Registros",
        "logs_save_btn": "Salvar em arquivo",
        "logs_window_title": "Registros",
        "auto_logging_label": "Registro automático",
        "logging_disabled_msg": "O registro está desativado.\nAtive \"Registro automático\" nas configurações.",
        "logs_pause_btn": "Pausar",
        "logs_resume_btn": "Retomar",
        "ctx_copy": "Copiar",
        "system_lang": "Idioma do sistema",
        "settings_section_general": "Geral",
        "settings_section_network": "Diagnóstico de rede",
        "settings_section_notifications": "Notificações",
    },
    "日本語 (Japanese)": {
        "tab_monitor": "モニター",
        "tab_speed": "速度テスト",
        "tab_settings": "設定",
        "tab_about": "詳細",
        "location": "場所",
        "vpn_on": "VPN/プロキシ有効 ",
        "vpn_off": "VPN/プロキシ無効 ",
        "sys_speed_title": "システムのインターネット速度",
        "traffic_title": "セッショントラフィック",
        "traffic_recv": "受信",
        "traffic_sent": "送信",
        "traffic_total": "合計",
        "net_monitor_btn": "プロセス監視",
        "net_monitor_title": "プロセスネットワーク監視",
        "net_monitor_process": "プロセス",
        "net_monitor_conns": "接続",
        "net_monitor_sess_recv": "↓ セッション",
        "net_monitor_sess_sent": "↑ セッション",
        "net_monitor_no_data": "アクティブな接続なし",
        "download": "ダウンロード",
        "upload": "アップロード",
        "latency_label": "遅延",
        "dns_title": "Ping応答チェック",
        "speed_check_title": "接続速度テスト",
        "settings_title": "設定",
        "speed_server_label": "測定サーバー:",
        "measure_btn": "測定",
        "cancel_btn": "キャンセル",
        "testing": "測定中...",
        "ver_title": "バージョン",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "プログラムについて",
        "about_desc": "リアルタイムでネットワーク状態を監視するオープンソースソフトです。システムのインターネット速度、主要プロバイダーのDNS応答時間を表示し、外部サーバーを通じた速度テストが可能です。",
        "links_title": "リンク",
        "ip_freq_label": "情報の更新間隔",
        "reset_btn": "設定をリセット",
        "reset_dialog_msg": "設定のみリセットしますか？それともカスタムping IPやテスト履歴を含む全データを削除しますか？",
        "reset_settings_only_btn": "設定のみリセット",
        "reset_all_btn": "全データを削除",
        "lang_label": "言語 (Language)",
        "startup_label": "OS起動時に実行",
        "tray_label": "トレイで動作",
        "notify_ip": "IP変更を通知",
        "notify_conn_loss_label": "接続切断時に通知",
        "notify_conn_lost_msg": "接続が切断されました",
        "notify_conn_restored_msg": "接続が回復しました",
        "notify_ip_msg": "IPアドレスが変更されました。新しい地域: {region}",
        "msg_ip_body": "新しいIP: ",
        "f_5s": "5秒",
        "f_10s": "10秒",
        "f_30s": "30秒",
        "f_1m": "1分",
        "f_2m": "2分",
        "f_5m": "5分",
        "f_10m": "10分",
        "tray_open": "開く",
        "tray_settings": "設定",
        "tray_speed_check": "速度テスト",
        "tray_exit": "終了",
        "custom_dns_label": "Ping対象 IP",
        "dns_name_ph": "名前",
        "dns_host_ph": "IP / ホスト",
        "dns_manage_btn": "管理",
        "dns_window_title": "Ping対象",
        "dns_add_btn": "追加",
        "speed_history_title": "テスト履歴",
        "speed_history_empty": "テストなし",
        "speed_hist_date": "日付",
        "speed_hist_server": "サーバー",
        "speed_history_clear": "クリア",
        "proc_monitor_bg_label": "バックグラウンドでプロセス監視",
        "tray_proc_monitor": "プロセス監視",
        "update_check_label": "起動時にアップデートを確認",
        "update_checking": "アップデートを確認中...",
        "update_uptodate": "最新バージョンをご利用中です",
        "update_available": "アップデート {ver} が利用可能です！インストール？",
        "update_error": "アップデートの確認に失敗しました",
        "update_manual_btn": "アップデートを確認",
        "update_popup_title": "アップデート利用可能",
        "update_popup_body": "バージョン {ver} が利用可能です。今すぐインストールしますか？",
        "update_install_btn": "インストール",
        "cancel_btn": "キャンセル",
        "update_progress_title": "更新中...",
        "update_downloading": "アップデートをダウンロード中...",
        "update_extracting": "ファイルを解凍中...",
        "update_restarting": "再起動中...",
        "notify_region_label": "地域変更を通知",
        "notify_region_msg": "地域変更: {region}",
        "always_on_top_label": "常に最前面に表示",
        "notify_conn_loss_label": "接続が切れたときに通知",
        "ip_server_label": "IP確認サーバー",
        "logs_btn": "ログ",
        "logs_save_btn": "ファイルに保存",
        "logs_window_title": "ログ",
        "auto_logging_label": "自動ログ記録",
        "logging_disabled_msg": "ログ記録が無効です。\n設定で「自動ログ記録」を有効にしてください。",
        "logs_pause_btn": "一時停止",
        "logs_resume_btn": "再開",
        "ctx_copy": "コピー",
        "system_lang": "システム言語",
        "settings_section_general": "一般",
        "settings_section_network": "ネットワーク診断",
        "settings_section_notifications": "通知",
    },
    "Türkçe (Turkish)": {
        "tab_monitor": "İzleyici",
        "tab_speed": "Hız Testi",
        "tab_settings": "Ayarlar",
        "tab_about": "Hakkında",
        "location": "Konum",
        "vpn_on": "VPN/Proxy etkin ",
        "vpn_off": "VPN/Proxy devre dışı ",
        "sys_speed_title": "Sistem İnternet Hızı",
        "traffic_title": "Oturum Trafik Kullanımı",
        "traffic_recv": "Alınan",
        "traffic_sent": "Gönderilen",
        "traffic_total": "Toplam",
        "net_monitor_btn": "Süreç İzleyici",
        "net_monitor_title": "Süreç Ağ İzleyici",
        "net_monitor_process": "Süreç",
        "net_monitor_conns": "Bağl.",
        "net_monitor_sess_recv": "↓ Oturum",
        "net_monitor_sess_sent": "↑ Oturum",
        "net_monitor_no_data": "Aktif bağlantı yok",
        "download": "İndirme",
        "upload": "Yükleme",
        "latency_label": "Gecikme",
        "dns_title": "Ping Gecikme Kontrolü",
        "speed_check_title": "İnternet Hız Testi",
        "settings_title": "Ayarlar",
        "speed_server_label": "Hız Testi Sunucusu:",
        "measure_btn": "Ölç",
        "cancel_btn": "İptal",
        "testing": "Test ediliyor...",
        "ver_title": "Sürüm",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "Program Hakkında",
        "about_desc": "Gerçek zamanlı ağ izleme için açık kaynaklı yazılım. Sistem internet hızını, popüler DNS sağlayıcılarına yanıt sürelerini görüntüler ve harici sunucular üzerinden bağlantı hızı testi yapmanıza olanak tanır.",
        "links_title": "Bağlantılar",
        "ip_freq_label": "Ağ Bilgisi Güncelleme Sıklığı",
        "reset_btn": "Varsayılana Sıfırla",
        "reset_dialog_msg": "Yalnızca ayarları sıfırlamak mı, yoksa tüm uygulama verilerini (özel ping IP'leri ve hız testi geçmişi dahil) silmek mi istiyorsunuz?",
        "reset_settings_only_btn": "Yalnızca ayarları sıfırla",
        "reset_all_btn": "Tüm verileri sil",
        "lang_label": "Dil (Language)",
        "startup_label": "Windows başlangıcında çalıştır",
        "tray_label": "Sistem tepsisinde çalış",
        "notify_ip": "IP değişiminde bildir",
        "notify_conn_loss_label": "Bağlantı kesildiğinde bildir",
        "notify_conn_lost_msg": "Bağlantı kesildi",
        "notify_conn_restored_msg": "Bağlantı yeniden kuruldu",
        "notify_ip_msg": "IP adresi değişti. Yeni bölge: {region}",
        "msg_ip_body": "Yeni IP: ",
        "f_5s": "5 saniye",
        "f_10s": "10 saniye",
        "f_30s": "30 saniye",
        "f_1m": "1 dakika",
        "f_2m": "2 dakika",
        "f_5m": "5 dakika",
        "f_10m": "10 dakika",
        "tray_open": "Aç",
        "tray_settings": "Ayarlar",
        "tray_speed_check": "Hız Testi",
        "tray_exit": "Çıkış",
        "custom_dns_label": "Ping hedefleri",
        "dns_name_ph": "Ad",
        "dns_host_ph": "IP / Host",
        "dns_manage_btn": "Yönet",
        "dns_window_title": "Ping Hedefleri",
        "dns_add_btn": "Ekle",
        "speed_history_title": "Test Geçmişi",
        "speed_history_empty": "Henüz test yok",
        "speed_hist_date": "Tarih",
        "speed_hist_server": "Sunucu",
        "speed_history_clear": "Temizle",
        "proc_monitor_bg_label": "Arka planda süreç izleme",
        "tray_proc_monitor": "Süreç İzleyici",
        "update_check_label": "Başlangıçta güncellemeleri kontrol et",
        "update_checking": "Güncellemeler kontrol ediliyor...",
        "update_uptodate": "En son sürümü kullanıyorsunuz",
        "update_available": "Güncelleme {ver} mevcut! Yükle?",
        "update_error": "Güncellemeler kontrol edilemedi",
        "update_manual_btn": "Güncellemeleri kontrol et",
        "update_popup_title": "Güncelleme mevcut",
        "update_popup_body": "Sürüm {ver} mevcut. Şimdi yükle?",
        "update_install_btn": "Yükle",
        "update_progress_title": "Güncelleniyor...",
        "update_downloading": "Güncelleme indiriliyor...",
        "update_extracting": "Dosyalar çıkarılıyor...",
        "update_restarting": "Yeniden başlatılıyor...",
        "notify_region_label": "Bölge değişiminde bildir",
        "notify_region_msg": "Bölge değişti: {region}",
        "always_on_top_label": "Her zaman üstte",
        "ip_server_label": "IP kontrol sunucusu",
        "logs_btn": "Günlükler",
        "logs_save_btn": "Dosyaya kaydet",
        "logs_window_title": "Günlükler",
        "auto_logging_label": "Otomatik günlük kaydı",
        "logging_disabled_msg": "Günlük kaydı devre dışı.\nAyarlarda \"Otomatik günlük kaydı\"nı etkinleştirin.",
        "logs_pause_btn": "Duraklat",
        "logs_resume_btn": "Devam et",
        "ctx_copy": "Kopyala",
        "system_lang": "Sistem dili",
        "settings_section_general": "Genel",
        "settings_section_network": "Ağ tanılaması",
        "settings_section_notifications": "Bildirimler",
    },
    "Srpski (Serbian)": {
        "tab_monitor": "Monitor",
        "tab_speed": "Test brzine",
        "tab_settings": "Podešavanja",
        "tab_about": "O programu",
        "location": "Lokacija",
        "vpn_on": "VPN/Proxy aktivan ",
        "vpn_off": "VPN/Proxy neaktivan ",
        "sys_speed_title": "Brzina interneta sistema",
        "traffic_title": "Potrošnja saobraćaja sesije",
        "traffic_recv": "Primljeno",
        "traffic_sent": "Poslato",
        "traffic_total": "Ukupno",
        "net_monitor_btn": "Monitor procesa",
        "net_monitor_title": "Monitor mrežnih procesa",
        "net_monitor_process": "Proces",
        "net_monitor_conns": "Veze",
        "net_monitor_sess_recv": "↓ Sesija",
        "net_monitor_sess_sent": "↑ Sesija",
        "net_monitor_no_data": "Nema aktivnih veza",
        "download": "Preuzimanje",
        "upload": "Slanje",
        "latency_label": "Kašnjenje",
        "dns_title": "Provjera ping kašnjenja",
        "speed_check_title": "Test brzine interneta",
        "settings_title": "Podešavanja",
        "speed_server_label": "Server za test brzine:",
        "measure_btn": "Izmjeri",
        "cancel_btn": "Otkaži",
        "testing": "Testiranje...",
        "ver_title": "Verzija",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "O programu",
        "about_desc": "Softver otvorenog koda za praćenje mreže u realnom vremenu. Prikazuje brzinu interneta sistema, vremena odziva DNS servera i omogućava testiranje brzine veze.",
        "links_title": "Linkovi",
        "ip_freq_label": "Interval ažuriranja mrežnih podataka",
        "reset_btn": "Resetuj na podrazumevano",
        "reset_dialog_msg": "Želite li da resetujete samo podešavanja ili da obrišete sve podatke aplikacije (uključujući prilagođene ping IP-ove i historiju testova)?",
        "reset_settings_only_btn": "Resetuj samo podešavanja",
        "reset_all_btn": "Obriši sve podatke",
        "lang_label": "Jezik (Language)",
        "startup_label": "Pokreni pri pokretanju Windowsa",
        "tray_label": "Radi u sistemskoj traci",
        "notify_ip": "Obavijesti pri promjeni IP-a",
        "notify_conn_loss_label": "Obavijesti pri gubitku veze",
        "notify_conn_lost_msg": "Veza izgubljena",
        "notify_conn_restored_msg": "Veza uspostavljena",
        "notify_ip_msg": "IP adresa promijenjena. Nova regija: {region}",
        "msg_ip_body": "Novi IP: ",
        "f_5s": "5 sekundi",
        "f_10s": "10 sekundi",
        "f_30s": "30 sekundi",
        "f_1m": "1 minut",
        "f_2m": "2 minute",
        "f_5m": "5 minuta",
        "f_10m": "10 minuta",
        "tray_open": "Otvori",
        "tray_settings": "Podešavanja",
        "tray_speed_check": "Test brzine",
        "tray_exit": "Izlaz",
        "custom_dns_label": "Ping ciljevi",
        "dns_name_ph": "Naziv",
        "dns_host_ph": "IP / Host",
        "dns_manage_btn": "Upravljaj",
        "dns_window_title": "Ping ciljevi",
        "dns_add_btn": "Dodaj",
        "speed_history_title": "Historija testova",
        "speed_history_empty": "Nema testova",
        "speed_hist_date": "Datum",
        "speed_hist_server": "Server",
        "speed_history_clear": "Obriši",
        "proc_monitor_bg_label": "Monitor procesa u pozadini",
        "tray_proc_monitor": "Monitor procesa",
        "update_check_label": "Provjeri ažuriranja pri pokretanju",
        "update_checking": "Provjera ažuriranja...",
        "update_uptodate": "Koristite najnoviju verziju",
        "update_available": "Dostupno ažuriranje {ver}! Instaliraj?",
        "update_error": "Provjera ažuriranja nije uspjela",
        "update_manual_btn": "Provjeri ažuriranja",
        "update_popup_title": "Dostupno ažuriranje",
        "update_popup_body": "Verzija {ver} je dostupna. Instalirati sada?",
        "update_install_btn": "Instaliraj",
        "update_progress_title": "Ažuriranje...",
        "update_downloading": "Preuzimanje ažuriranja...",
        "update_extracting": "Raspakivanje fajlova...",
        "update_restarting": "Ponovo pokretanje...",
        "notify_region_label": "Obavijesti pri promjeni regije",
        "notify_region_msg": "Regija promijenjena: {region}",
        "always_on_top_label": "Uvijek na vrhu",
        "ip_server_label": "Server za proveru IP-a",
        "logs_btn": "Logovi",
        "logs_save_btn": "Sačuvaj u fajl",
        "logs_window_title": "Logovi",
        "auto_logging_label": "Automatsko logovanje",
        "logging_disabled_msg": "Logovanje je onemogućeno.\nAktivujte \"Automatsko logovanje\" u podešavanjima.",
        "logs_pause_btn": "Pauza",
        "logs_resume_btn": "Nastavi",
        "ctx_copy": "Kopiraj",
        "system_lang": "Sistemski jezik",
        "settings_section_general": "Opšte",
        "settings_section_network": "Dijagnostika mreže",
        "settings_section_notifications": "Obaveštenja",
    },
    "Қазақша (Kazakh)": {
        "tab_monitor": "Бақылау",
        "tab_speed": "Жылдамдық тексеру",
        "tab_settings": "Баптаулар",
        "tab_about": "Бағдарлама туралы",
        "location": "Орналасу",
        "vpn_on": "VPN/Proxy қосулы ",
        "vpn_off": "VPN/Proxy өшірулі ",
        "sys_speed_title": "Жүйелік интернет жылдамдығы",
        "traffic_title": "Сессия трафик шығыны",
        "traffic_recv": "Алынды",
        "traffic_sent": "Жіберілді",
        "traffic_total": "Жалпы",
        "net_monitor_btn": "Процесс мониторы",
        "net_monitor_title": "Процесс желі мониторы",
        "net_monitor_process": "Процесс",
        "net_monitor_conns": "Байл.",
        "net_monitor_sess_recv": "↓ Сессия",
        "net_monitor_sess_sent": "↑ Сессия",
        "net_monitor_no_data": "Белсенді байланыс жоқ",
        "download": "Жүктеу",
        "upload": "Жіберу",
        "latency_label": "Кідіріс",
        "dns_title": "Ping кідірісін тексеру",
        "speed_check_title": "Интернет жылдамдығын тексеру",
        "settings_title": "Баптаулар",
        "speed_server_label": "Жылдамдық тексеру сервері:",
        "measure_btn": "Өлшеу",
        "cancel_btn": "Болдырмау",
        "testing": "Тексерілуде...",
        "ver_title": "Нұсқа",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "Бағдарлама туралы",
        "about_desc": "Желіні нақты уақытта бақылауға арналған ашық бастапқы кодты бағдарлама. Жүйелік интернет жылдамдығын, DNS жауап уақыттарын көрсетеді және сыртқы серверлер арқылы байланыс жылдамдығын тексеруге мүмкіндік береді.",
        "links_title": "Сілтемелер",
        "ip_freq_label": "Желі ақпаратын жаңарту жиілігі",
        "reset_btn": "Әдепкіге қайтару",
        "reset_dialog_msg": "Тек баптауларды қайтару немесе барлық деректерді жою (арнаулы ping IP және жылдамдық тексеру тарихы) керек пе?",
        "reset_settings_only_btn": "Тек баптауларды қайтару",
        "reset_all_btn": "Барлық деректерді жою",
        "lang_label": "Тіл (Language)",
        "startup_label": "Windows іске қосылғанда жұмыс істеу",
        "tray_label": "Трейде жұмыс істеу",
        "notify_ip": "IP өзгерісін хабарлау",
        "notify_conn_loss_label": "Байланыс үзілгенде хабарлау",
        "notify_conn_lost_msg": "Байланыс үзілді",
        "notify_conn_restored_msg": "Байланыс қалпына келді",
        "notify_ip_msg": "IP мекенжайы өзгерді. Жаңа аймақ: {region}",
        "msg_ip_body": "Жаңа IP: ",
        "f_5s": "5 секунд",
        "f_10s": "10 секунд",
        "f_30s": "30 секунд",
        "f_1m": "1 минут",
        "f_2m": "2 минут",
        "f_5m": "5 минут",
        "f_10m": "10 минут",
        "tray_open": "Ашу",
        "tray_settings": "Баптаулар",
        "tray_speed_check": "Жылдамдық тексеру",
        "tray_exit": "Шығу",
        "custom_dns_label": "Ping нысандары",
        "dns_name_ph": "Атауы",
        "dns_host_ph": "IP / Хост",
        "dns_manage_btn": "Басқару",
        "dns_window_title": "Ping нысандары",
        "dns_add_btn": "Қосу",
        "speed_history_title": "Тексеру тарихы",
        "speed_history_empty": "Тексеру жоқ",
        "speed_hist_date": "Күні",
        "speed_hist_server": "Сервер",
        "speed_history_clear": "Тазалау",
        "proc_monitor_bg_label": "Процессті фонда бақылау",
        "tray_proc_monitor": "Процесс мониторы",
        "update_check_label": "Іске қосылғанда жаңартуларды тексеру",
        "update_checking": "Жаңартулар тексерілуде...",
        "update_uptodate": "Соңғы нұсқаны пайдаланасыз",
        "update_available": "Жаңарту {ver} қол жетімді! Орнату?",
        "update_error": "Жаңартуларды тексеру сәтсіз",
        "update_manual_btn": "Жаңартуларды тексеру",
        "update_popup_title": "Жаңарту қол жетімді",
        "update_popup_body": "{ver} нұсқасы қол жетімді. Қазір орнату?",
        "update_install_btn": "Орнату",
        "update_progress_title": "Жаңартылуда...",
        "update_downloading": "Жаңарту жүктелуде...",
        "update_extracting": "Файлдар шығарылуда...",
        "update_restarting": "Қайта іске қосылуда...",
        "notify_region_label": "Аймақ өзгерісін хабарлау",
        "notify_region_msg": "Аймақ өзгерді: {region}",
        "always_on_top_label": "Әрқашан жоғарыда",
        "ip_server_label": "IP тексеру сервері",
        "logs_btn": "Журналдар",
        "logs_save_btn": "Файлға сақтау",
        "logs_window_title": "Журналдар",
        "auto_logging_label": "Автоматты тіркеу",
        "logging_disabled_msg": "Тіркеу өшірілген.\nПараметрлерде \"Автоматты тіркеу\" белсендіріңіз.",
        "logs_pause_btn": "Кідірту",
        "logs_resume_btn": "Жалғастыру",
        "ctx_copy": "Көшіру",
        "system_lang": "Жүйе тілі",
        "settings_section_general": "Жалпы",
        "settings_section_network": "Желі диагностикасы",
        "settings_section_notifications": "Хабарландырулар",
    },
    "Беларуская (Belarusian)": {
        "tab_monitor": "Манітор",
        "tab_speed": "Праверка хуткасці",
        "tab_settings": "Налады",
        "tab_about": "Пра праграму",
        "location": "Месцазнаходжанне",
        "vpn_on": "VPN/Proxy уключаны ",
        "vpn_off": "VPN/Proxy выключаны ",
        "sys_speed_title": "Хуткасць інтэрнэту сістэмы",
        "traffic_title": "Выкарыстанне трафіку за сесію",
        "traffic_recv": "Атрымана",
        "traffic_sent": "Адпраўлена",
        "traffic_total": "Усяго",
        "net_monitor_btn": "Манітор працэсаў",
        "net_monitor_title": "Сеткавы манітор працэсаў",
        "net_monitor_process": "Працэс",
        "net_monitor_conns": "Злучэнні",
        "net_monitor_sess_recv": "↓ Сесія",
        "net_monitor_sess_sent": "↑ Сесія",
        "net_monitor_no_data": "Няма актыўных злучэнняў",
        "download": "Загрузка",
        "upload": "Выгрузка",
        "latency_label": "Затрымка",
        "dns_title": "Праверка затрымкі Ping",
        "speed_check_title": "Тэст хуткасці інтэрнэту",
        "settings_title": "Налады",
        "speed_server_label": "Сервер тэсту хуткасці:",
        "measure_btn": "Вымераць",
        "cancel_btn": "Адмена",
        "testing": "Тэсціруецца...",
        "ver_title": "Версія",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "Пра праграму",
        "about_desc": "Праграмнае забеспячэнне з адкрытым зыходным кодам для маніторынгу сеткі ў рэжыме рэальнага часу. Паказвае хуткасць інтэрнэту сістэмы, час адказу DNS і дазваляе тэставаць хуткасць злучэння.",
        "links_title": "Спасылкі",
        "ip_freq_label": "Інтэрвал абнаўлення сеткавых дадзеных",
        "reset_btn": "Скінуць да стандартнага",
        "reset_dialog_msg": "Вы хочаце скінуць толькі налады або выдаліць усе дадзеныя праграмы (уключаючы карыстальніцкія ping IP і гісторыю тэстаў)?",
        "reset_settings_only_btn": "Скінуць толькі налады",
        "reset_all_btn": "Выдаліць усе дадзеныя",
        "lang_label": "Мова (Language)",
        "startup_label": "Запускаць пры старце Windows",
        "tray_label": "Працаваць у трэі",
        "notify_ip": "Апавяшчаць пры змене IP",
        "notify_conn_loss_label": "Апавяшчаць пры страце сувязі",
        "notify_conn_lost_msg": "Сувязь страчана",
        "notify_conn_restored_msg": "Сувязь адноўлена",
        "notify_ip_msg": "IP-адрас зменены. Новы рэгіён: {region}",
        "msg_ip_body": "Новы IP: ",
        "f_5s": "5 секунд",
        "f_10s": "10 секунд",
        "f_30s": "30 секунд",
        "f_1m": "1 хвіліна",
        "f_2m": "2 хвіліны",
        "f_5m": "5 хвілін",
        "f_10m": "10 хвілін",
        "tray_open": "Адкрыць",
        "tray_settings": "Налады",
        "tray_speed_check": "Праверка хуткасці",
        "tray_exit": "Выйсці",
        "custom_dns_label": "Мэты Ping",
        "dns_name_ph": "Назва",
        "dns_host_ph": "IP / Хост",
        "dns_manage_btn": "Кіраваць",
        "dns_window_title": "Мэты Ping",
        "dns_add_btn": "Дадаць",
        "speed_history_title": "Гісторыя тэстаў",
        "speed_history_empty": "Тэстаў няма",
        "speed_hist_date": "Дата",
        "speed_hist_server": "Сервер",
        "speed_history_clear": "Ачысціць",
        "proc_monitor_bg_label": "Манітор працэсаў у фоне",
        "tray_proc_monitor": "Манітор працэсаў",
        "update_check_label": "Праверяць абнаўленні пры запуску",
        "update_checking": "Праверка абнаўленняў...",
        "update_uptodate": "Вы выкарыстоўваеце апошнюю версію",
        "update_available": "Даступна абнаўленне {ver}! Усталяваць?",
        "update_error": "Не ўдалося праверыць абнаўленні",
        "update_manual_btn": "Праверыць абнаўленні",
        "update_popup_title": "Даступна абнаўленне",
        "update_popup_body": "Версія {ver} даступна. Усталяваць зараз?",
        "update_install_btn": "Усталяваць",
        "update_progress_title": "Абнаўленне...",
        "update_downloading": "Спампоўка абнаўлення...",
        "update_extracting": "Распакоўка файлаў...",
        "update_restarting": "Перазапуск...",
        "notify_region_label": "Апавяшчаць пры змене рэгіёну",
        "notify_region_msg": "Рэгіён зменены: {region}",
        "always_on_top_label": "Заўсёды зверху",
        "ip_server_label": "Сервер праверкі IP",
        "logs_btn": "Журналы",
        "logs_save_btn": "Захаваць у файл",
        "logs_window_title": "Журналы",
        "auto_logging_label": "Аўтаматычнае запісванне",
        "logging_disabled_msg": "Запісванне адключана.\nАктывуйце параметр \"Аўтаматычнае запісванне\" ў наладах.",
        "logs_pause_btn": "Паўза",
        "logs_resume_btn": "Працягнуць",
        "ctx_copy": "Капіяваць",
        "system_lang": "Мова сістэмы",
        "settings_section_general": "Агульныя",
        "settings_section_network": "Дыягностыка сеткі",
        "settings_section_notifications": "Апавяшчэнні",
    },
    "Čeština (Czech)": {
        "tab_monitor": "Monitor",
        "tab_speed": "Test rychlosti",
        "tab_settings": "Nastavení",
        "tab_about": "O programu",
        "location": "Poloha",
        "vpn_on": "VPN/Proxy zapnuto ",
        "vpn_off": "VPN/Proxy vypnuto ",
        "sys_speed_title": "Rychlost internetu systému",
        "traffic_title": "Spotřeba dat relace",
        "traffic_recv": "Přijato",
        "traffic_sent": "Odesláno",
        "traffic_total": "Celkem",
        "net_monitor_btn": "Monitor procesů",
        "net_monitor_title": "Monitor síťových procesů",
        "net_monitor_process": "Proces",
        "net_monitor_conns": "Spoj.",
        "net_monitor_sess_recv": "↓ Relace",
        "net_monitor_sess_sent": "↑ Relace",
        "net_monitor_no_data": "Žádná aktivní připojení",
        "download": "Stahování",
        "upload": "Nahrávání",
        "latency_label": "Latence",
        "dns_title": "Kontrola latence Ping",
        "speed_check_title": "Test rychlosti internetu",
        "settings_title": "Nastavení",
        "speed_server_label": "Server pro test rychlosti:",
        "measure_btn": "Změřit",
        "cancel_btn": "Zrušit",
        "testing": "Testování...",
        "ver_title": "Verze",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "O programu",
        "about_desc": "Open-source software pro monitorování sítě v reálném čase. Zobrazuje rychlost internetu systému, doby odezvy DNS a umožňuje testovat rychlost připojení přes externí servery.",
        "links_title": "Odkazy",
        "ip_freq_label": "Interval aktualizace síťových informací",
        "reset_btn": "Obnovit výchozí nastavení",
        "reset_dialog_msg": "Chcete obnovit pouze nastavení, nebo smazat všechna data aplikace (včetně vlastních ping IP a historie testů)?",
        "reset_settings_only_btn": "Obnovit pouze nastavení",
        "reset_all_btn": "Smazat všechna data",
        "lang_label": "Jazyk (Language)",
        "startup_label": "Spustit při startu Windows",
        "tray_label": "Pracovat na liště",
        "notify_ip": "Upozornit při změně IP",
        "notify_conn_loss_label": "Upozornit při ztrátě připojení",
        "notify_conn_lost_msg": "Připojení ztraceno",
        "notify_conn_restored_msg": "Připojení obnoveno",
        "notify_ip_msg": "IP adresa změněna. Nová oblast: {region}",
        "msg_ip_body": "Nová IP: ",
        "f_5s": "5 sekund",
        "f_10s": "10 sekund",
        "f_30s": "30 sekund",
        "f_1m": "1 minuta",
        "f_2m": "2 minuty",
        "f_5m": "5 minut",
        "f_10m": "10 minut",
        "tray_open": "Otevřít",
        "tray_settings": "Nastavení",
        "tray_speed_check": "Test rychlosti",
        "tray_exit": "Konec",
        "custom_dns_label": "Cíle Ping",
        "dns_name_ph": "Název",
        "dns_host_ph": "IP / Host",
        "dns_manage_btn": "Spravovat",
        "dns_window_title": "Cíle Ping",
        "dns_add_btn": "Přidat",
        "speed_history_title": "Historie testů",
        "speed_history_empty": "Žádné testy",
        "speed_hist_date": "Datum",
        "speed_hist_server": "Server",
        "speed_history_clear": "Vymazat",
        "proc_monitor_bg_label": "Monitor procesů na pozadí",
        "tray_proc_monitor": "Monitor procesů",
        "update_check_label": "Kontrolovat aktualizace při spuštění",
        "update_checking": "Kontrola aktualizací...",
        "update_uptodate": "Používáte nejnovější verzi",
        "update_available": "Aktualizace {ver} je k dispozici! Nainstalovat?",
        "update_error": "Kontrola aktualizací se nezdařila",
        "update_manual_btn": "Zkontrolovat aktualizace",
        "update_popup_title": "Aktualizace k dispozici",
        "update_popup_body": "Verze {ver} je k dispozici. Nainstalovat nyní?",
        "update_install_btn": "Nainstalovat",
        "update_progress_title": "Aktualizace...",
        "update_downloading": "Stahování aktualizace...",
        "update_extracting": "Rozbalování souborů...",
        "update_restarting": "Restartování...",
        "notify_region_label": "Upozornit při změně oblasti",
        "notify_region_msg": "Oblast změněna: {region}",
        "always_on_top_label": "Vždy nahoře",
        "ip_server_label": "Server pro kontrolu IP",
        "logs_btn": "Protokoly",
        "logs_save_btn": "Uložit do souboru",
        "logs_window_title": "Protokoly",
        "auto_logging_label": "Automatické protokolování",
        "logging_disabled_msg": "Protokolování je vypnuto.\nAktivujte \"Automatické protokolování\" v nastavení.",
        "logs_pause_btn": "Pozastavit",
        "logs_resume_btn": "Pokračovat",
        "ctx_copy": "Kopírovat",
        "system_lang": "Jazyk systému",
        "settings_section_general": "Obecné",
        "settings_section_network": "Diagnostika sítě",
        "settings_section_notifications": "Oznámení",
    },
    "한국어 (Korean)": {
        "tab_monitor": "모니터",
        "tab_speed": "속도 측정",
        "tab_settings": "설정",
        "tab_about": "정보",
        "location": "위치",
        "vpn_on": "VPN/Proxy 활성화 ",
        "vpn_off": "VPN/Proxy 비활성화 ",
        "sys_speed_title": "시스템 인터넷 속도",
        "traffic_title": "세션 트래픽 사용량",
        "traffic_recv": "수신",
        "traffic_sent": "송신",
        "traffic_total": "합계",
        "net_monitor_btn": "프로세스 모니터",
        "net_monitor_title": "프로세스 네트워크 모니터",
        "net_monitor_process": "프로세스",
        "net_monitor_conns": "연결",
        "net_monitor_sess_recv": "↓ 세션",
        "net_monitor_sess_sent": "↑ 세션",
        "net_monitor_no_data": "활성 연결 없음",
        "download": "다운로드",
        "upload": "업로드",
        "latency_label": "지연",
        "dns_title": "Ping 지연 확인",
        "speed_check_title": "인터넷 속도 테스트",
        "settings_title": "설정",
        "speed_server_label": "속도 테스트 서버:",
        "measure_btn": "측정",
        "cancel_btn": "취소",
        "testing": "테스트 중...",
        "ver_title": "버전",
        "ver_label": "0.1 Beta",
        "app_name": "JB NetTracker",
        "about_title": "프로그램 정보",
        "about_desc": "실시간 네트워크 모니터링을 위한 오픈 소스 소프트웨어. 시스템 인터넷 속도, DNS 응답 시간을 표시하고 외부 서버를 통해 연결 속도를 테스트할 수 있습니다.",
        "links_title": "링크",
        "ip_freq_label": "네트워크 정보 업데이트 간격",
        "reset_btn": "기본값으로 초기화",
        "reset_dialog_msg": "설정만 초기화하시겠습니까, 아니면 모든 앱 데이터(사용자 정의 ping IP 및 속도 테스트 기록 포함)를 삭제하시겠습니까?",
        "reset_settings_only_btn": "설정만 초기화",
        "reset_all_btn": "모든 데이터 삭제",
        "lang_label": "언어 (Language)",
        "startup_label": "Windows 시작 시 실행",
        "tray_label": "트레이에서 실행",
        "notify_ip": "IP 변경 시 알림",
        "notify_conn_loss_label": "연결 끊김 시 알림",
        "notify_conn_lost_msg": "연결이 끊겼습니다",
        "notify_conn_restored_msg": "연결이 복원되었습니다",
        "notify_ip_msg": "IP 주소가 변경되었습니다. 새 지역: {region}",
        "msg_ip_body": "새 IP: ",
        "f_5s": "5초",
        "f_10s": "10초",
        "f_30s": "30초",
        "f_1m": "1분",
        "f_2m": "2분",
        "f_5m": "5분",
        "f_10m": "10분",
        "tray_open": "열기",
        "tray_settings": "설정",
        "tray_speed_check": "속도 측정",
        "tray_exit": "종료",
        "custom_dns_label": "Ping 대상",
        "dns_name_ph": "이름",
        "dns_host_ph": "IP / 호스트",
        "dns_manage_btn": "관리",
        "dns_window_title": "Ping 대상",
        "dns_add_btn": "추가",
        "speed_history_title": "테스트 기록",
        "speed_history_empty": "테스트 없음",
        "speed_hist_date": "날짜",
        "speed_hist_server": "서버",
        "speed_history_clear": "지우기",
        "proc_monitor_bg_label": "백그라운드 프로세스 모니터",
        "tray_proc_monitor": "프로세스 모니터",
        "update_check_label": "시작 시 업데이트 확인",
        "update_checking": "업데이트 확인 중...",
        "update_uptodate": "최신 버전을 사용 중입니다",
        "update_available": "업데이트 {ver} 사용 가능! 설치?",
        "update_error": "업데이트 확인 실패",
        "update_manual_btn": "업데이트 확인",
        "update_popup_title": "업데이트 사용 가능",
        "update_popup_body": "버전 {ver}을 사용할 수 있습니다. 지금 설치하시겠습니까?",
        "update_install_btn": "설치",
        "update_progress_title": "업데이트 중...",
        "update_downloading": "업데이트 다운로드 중...",
        "update_extracting": "파일 압축 해제 중...",
        "update_restarting": "재시작 중...",
        "notify_region_label": "지역 변경 시 알림",
        "notify_region_msg": "지역 변경됨: {region}",
        "always_on_top_label": "항상 위에 표시",
        "ip_server_label": "IP 확인 서버",
        "logs_btn": "로그",
        "logs_save_btn": "파일로 저장",
        "logs_window_title": "로그",
        "auto_logging_label": "자동 로깅",
        "logging_disabled_msg": "로깅이 비활성화되어 있습니다.\n설정에서 \"자동 로깅\"을 활성화하세요.",
        "logs_pause_btn": "일시정지",
        "logs_resume_btn": "재개",
        "ctx_copy": "복사",
        "system_lang": "시스템 언어",
        "settings_section_general": "일반",
        "settings_section_network": "네트워크 진단",
        "settings_section_notifications": "알림",
    },
}
